### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by Stargator** [Stargator/probot-arborist#1]
# Goals for Project

Ordered by Priority:

- [x] Arborist starts properly
- [x] Arborist catches events when a branch is created
- [x] Arborist catches events when an issue is created by the bot
- [x] Arborist creates an issue for a branch that doesn't meet naming convention
- [ ] Arborist reads the config file ([used the setting.js file from probot-settings](https://github.com/probot/settings/blob/master/lib/settings.js), See #4 
- [ ] Arborist validates the branch against the configuration setting, #5
- [ ] Arborist updates existing issue for any new branches that don't meet naming convention, See #11
- [ ] Arborist creates an issue for Pull Request that is closed, but the branch hasn't been deleted after a period of time, See #12
- [ ] Arborist creates an issue for Pull Request that is merged, but the branch hasn't been deleted after a period of time, See #13
- [ ] Arborist updates existing issue for any Pull Requests that are closed, but the branch hasn't been deleted, See #14
- [ ] Arborist updates existing issue for any Pull Requests that are merged, but the branch hasn't been deleted, See #15
- [ ] Arborist monitors created issues for any that get closed/completed, See #7
- [ ] Arborist creates new issues when conditions are met after previous issues are closed. #8
- [ ] Create travis config for Arborist builds ([example1](https://github.com/probot/settings/blob/master/.travis.yml), [example2](https://github.com/probot/dco/blob/master/.travis.yml)), See #6
- [ ] Update the Wiki with needed information, See #9
- [ ] Add support for Arborist deleting branches based on configuration setting. (Currently, [node-gtthub](https://mikedeboer.github.io/node-github/) doesn't support deleting branches)
- [ ] If all the branches listed in an issue are deleted, Arborist closes the issue (Currently, [node-gtthub](https://mikedeboer.github.io/node-github/) doesn't support closing issues)
